out_dir: results/Cor44-GPS
metric_best: loss
wandb:
  use: False
  project: ER  # W&B project for debugging runs.
dataset:
  format: PyG-Cor44-10
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+LapPE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 1
  edge_encoder_bn: False
pretrained:
  dir: results/Cor44-GPS/train
  reset_prediction_head: False
train:
  mode: inference-only
  batch_size: 200
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GCN+Transformer  # CustomGatedGCN+Performer
  layers: 3
  n_heads: 4
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.0
  layer_norm: False
  batch_norm: True
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 256
  layer_type: gcnconv
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False

