out_dir: results/ER-VN
metric_best: loss
wandb:
  use: True
  project: ER
dataset:
  format: PyG-ER10
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode #+LapPE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 1
  edge_encoder_bn: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
train:
  mode: inference-only
  batch_size: 10
pretrained:
  dir: results/ER-VN/train
  reset_prediction_head: False
model:
  type: custom_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_post_mp: 2
  layers_mp: 3
  dim_inner: 256
  layer_type: gcnconv
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  residual: True
  normalize_adj: False
  use_vn: True
  vn_pooling: add
  vn_norm: none
